### ISSUE TITLE
Update InfoPlist.strings in Bulgarian

### ISSUE THREAD

**Issue by levinli303** [levinli303/MobileCelestia#4]
https://github.com/levinli303/MobileCelestia/blob/master/MobileCelestia/Resources/bg.lproj/InfoPlist.strings

The original string in English has changed from "Permission is needed to save screenshots to Photo Library." to "Permission is needed to save screenshots to the Photos app."

@RacerBG can you change the translation accordingly. Photos should be in between quotation marks (as I observed from other translations).

**Comment by RacerBG** [comment]
@levinli303 Here you go: `"Нужно е разрешение за запазване в приложението Photos."`
